/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TemasRedacaoAdminRouteImport } from './routes/temas-redacao-admin'
import { Route as SimuladosAdminRouteImport } from './routes/simulados-admin'
import { Route as SimuladosRouteImport } from './routes/simulados'
import { Route as RedacoesAdminRouteImport } from './routes/redacoes-admin'
import { Route as RedacoesRouteImport } from './routes/redacoes'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as NotasAdminRouteImport } from './routes/notas-admin'
import { Route as MentoriasGrupoAdminRouteImport } from './routes/mentorias-grupo-admin'
import { Route as MentoriasGrupoRouteImport } from './routes/mentorias-grupo'
import { Route as MentoriasAdminRouteImport } from './routes/mentorias-admin'
import { Route as MentoriasRouteImport } from './routes/mentorias'
import { Route as MateriaisAdminRouteImport } from './routes/materiais-admin'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as LembretesAdminRouteImport } from './routes/lembretes-admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AulasAdminRouteImport } from './routes/aulas-admin'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as AulaAoVivoAdminRouteImport } from './routes/aula-ao-vivo-admin'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmBreveSecaoRouteImport } from './routes/em-breve.$secao'
import { Route as ConteudoSecaoRouteImport } from './routes/conteudo.$secao'
import { Route as ConteudoAdminSecaoRouteImport } from './routes/conteudo-admin.$secao'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasRedacaoAdminRoute = TemasRedacaoAdminRouteImport.update({
  id: '/temas-redacao-admin',
  path: '/temas-redacao-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladosAdminRoute = SimuladosAdminRouteImport.update({
  id: '/simulados-admin',
  path: '/simulados-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladosRoute = SimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacoesAdminRoute = RedacoesAdminRouteImport.update({
  id: '/redacoes-admin',
  path: '/redacoes-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacoesRoute = RedacoesRouteImport.update({
  id: '/redacoes',
  path: '/redacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasAdminRoute = NotasAdminRouteImport.update({
  id: '/notas-admin',
  path: '/notas-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasGrupoAdminRoute = MentoriasGrupoAdminRouteImport.update({
  id: '/mentorias-grupo-admin',
  path: '/mentorias-grupo-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasGrupoRoute = MentoriasGrupoRouteImport.update({
  id: '/mentorias-grupo',
  path: '/mentorias-grupo',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasAdminRoute = MentoriasAdminRouteImport.update({
  id: '/mentorias-admin',
  path: '/mentorias-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasRoute = MentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisAdminRoute = MateriaisAdminRouteImport.update({
  id: '/materiais-admin',
  path: '/materiais-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const LembretesAdminRoute = LembretesAdminRouteImport.update({
  id: '/lembretes-admin',
  path: '/lembretes-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasAdminRoute = AulasAdminRouteImport.update({
  id: '/aulas-admin',
  path: '/aulas-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaAoVivoAdminRoute = AulaAoVivoAdminRouteImport.update({
  id: '/aula-ao-vivo-admin',
  path: '/aula-ao-vivo-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveSecaoRoute = EmBreveSecaoRouteImport.update({
  id: '/em-breve/$secao',
  path: '/em-breve/$secao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoSecaoRoute = ConteudoSecaoRouteImport.update({
  id: '/conteudo/$secao',
  path: '/conteudo/$secao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoAdminSecaoRoute = ConteudoAdminSecaoRouteImport.update({
  id: '/conteudo-admin/$secao',
  path: '/conteudo-admin/$secao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/aula-ao-vivo-admin': typeof AulaAoVivoAdminRoute
  '/aulas': typeof AulasRoute
  '/aulas-admin': typeof AulasAdminRoute
  '/calendario': typeof CalendarioRoute
  '/dashboard': typeof DashboardRoute
  '/lembretes-admin': typeof LembretesAdminRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/materiais-admin': typeof MateriaisAdminRoute
  '/mentorias': typeof MentoriasRoute
  '/mentorias-admin': typeof MentoriasAdminRoute
  '/mentorias-grupo': typeof MentoriasGrupoRoute
  '/mentorias-grupo-admin': typeof MentoriasGrupoAdminRoute
  '/notas-admin': typeof NotasAdminRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
  '/redacoes': typeof RedacoesRoute
  '/redacoes-admin': typeof RedacoesAdminRoute
  '/simulados': typeof SimuladosRoute
  '/simulados-admin': typeof SimuladosAdminRoute
  '/temas-redacao-admin': typeof TemasRedacaoAdminRoute
  '/termos': typeof TermosRoute
  '/conteudo-admin/$secao': typeof ConteudoAdminSecaoRoute
  '/conteudo/$secao': typeof ConteudoSecaoRoute
  '/em-breve/$secao': typeof EmBreveSecaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/aula-ao-vivo-admin': typeof AulaAoVivoAdminRoute
  '/aulas': typeof AulasRoute
  '/aulas-admin': typeof AulasAdminRoute
  '/calendario': typeof CalendarioRoute
  '/dashboard': typeof DashboardRoute
  '/lembretes-admin': typeof LembretesAdminRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/materiais-admin': typeof MateriaisAdminRoute
  '/mentorias': typeof MentoriasRoute
  '/mentorias-admin': typeof MentoriasAdminRoute
  '/mentorias-grupo': typeof MentoriasGrupoRoute
  '/mentorias-grupo-admin': typeof MentoriasGrupoAdminRoute
  '/notas-admin': typeof NotasAdminRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
  '/redacoes': typeof RedacoesRoute
  '/redacoes-admin': typeof RedacoesAdminRoute
  '/simulados': typeof SimuladosRoute
  '/simulados-admin': typeof SimuladosAdminRoute
  '/temas-redacao-admin': typeof TemasRedacaoAdminRoute
  '/termos': typeof TermosRoute
  '/conteudo-admin/$secao': typeof ConteudoAdminSecaoRoute
  '/conteudo/$secao': typeof ConteudoSecaoRoute
  '/em-breve/$secao': typeof EmBreveSecaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/aula-ao-vivo-admin': typeof AulaAoVivoAdminRoute
  '/aulas': typeof AulasRoute
  '/aulas-admin': typeof AulasAdminRoute
  '/calendario': typeof CalendarioRoute
  '/dashboard': typeof DashboardRoute
  '/lembretes-admin': typeof LembretesAdminRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/materiais-admin': typeof MateriaisAdminRoute
  '/mentorias': typeof MentoriasRoute
  '/mentorias-admin': typeof MentoriasAdminRoute
  '/mentorias-grupo': typeof MentoriasGrupoRoute
  '/mentorias-grupo-admin': typeof MentoriasGrupoAdminRoute
  '/notas-admin': typeof NotasAdminRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
  '/redacoes': typeof RedacoesRoute
  '/redacoes-admin': typeof RedacoesAdminRoute
  '/simulados': typeof SimuladosRoute
  '/simulados-admin': typeof SimuladosAdminRoute
  '/temas-redacao-admin': typeof TemasRedacaoAdminRoute
  '/termos': typeof TermosRoute
  '/conteudo-admin/$secao': typeof ConteudoAdminSecaoRoute
  '/conteudo/$secao': typeof ConteudoSecaoRoute
  '/em-breve/$secao': typeof EmBreveSecaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aguardando-aprovacao'
    | '/aula-ao-vivo-admin'
    | '/aulas'
    | '/aulas-admin'
    | '/calendario'
    | '/dashboard'
    | '/lembretes-admin'
    | '/lgpd'
    | '/login'
    | '/materiais'
    | '/materiais-admin'
    | '/mentorias'
    | '/mentorias-admin'
    | '/mentorias-grupo'
    | '/mentorias-grupo-admin'
    | '/notas-admin'
    | '/privacidade'
    | '/professor'
    | '/progresso'
    | '/redacoes'
    | '/redacoes-admin'
    | '/simulados'
    | '/simulados-admin'
    | '/temas-redacao-admin'
    | '/termos'
    | '/conteudo-admin/$secao'
    | '/conteudo/$secao'
    | '/em-breve/$secao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aguardando-aprovacao'
    | '/aula-ao-vivo-admin'
    | '/aulas'
    | '/aulas-admin'
    | '/calendario'
    | '/dashboard'
    | '/lembretes-admin'
    | '/lgpd'
    | '/login'
    | '/materiais'
    | '/materiais-admin'
    | '/mentorias'
    | '/mentorias-admin'
    | '/mentorias-grupo'
    | '/mentorias-grupo-admin'
    | '/notas-admin'
    | '/privacidade'
    | '/professor'
    | '/progresso'
    | '/redacoes'
    | '/redacoes-admin'
    | '/simulados'
    | '/simulados-admin'
    | '/temas-redacao-admin'
    | '/termos'
    | '/conteudo-admin/$secao'
    | '/conteudo/$secao'
    | '/em-breve/$secao'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aguardando-aprovacao'
    | '/aula-ao-vivo-admin'
    | '/aulas'
    | '/aulas-admin'
    | '/calendario'
    | '/dashboard'
    | '/lembretes-admin'
    | '/lgpd'
    | '/login'
    | '/materiais'
    | '/materiais-admin'
    | '/mentorias'
    | '/mentorias-admin'
    | '/mentorias-grupo'
    | '/mentorias-grupo-admin'
    | '/notas-admin'
    | '/privacidade'
    | '/professor'
    | '/progresso'
    | '/redacoes'
    | '/redacoes-admin'
    | '/simulados'
    | '/simulados-admin'
    | '/temas-redacao-admin'
    | '/termos'
    | '/conteudo-admin/$secao'
    | '/conteudo/$secao'
    | '/em-breve/$secao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  AulaAoVivoAdminRoute: typeof AulaAoVivoAdminRoute
  AulasRoute: typeof AulasRoute
  AulasAdminRoute: typeof AulasAdminRoute
  CalendarioRoute: typeof CalendarioRoute
  DashboardRoute: typeof DashboardRoute
  LembretesAdminRoute: typeof LembretesAdminRoute
  LgpdRoute: typeof LgpdRoute
  LoginRoute: typeof LoginRoute
  MateriaisRoute: typeof MateriaisRoute
  MateriaisAdminRoute: typeof MateriaisAdminRoute
  MentoriasRoute: typeof MentoriasRoute
  MentoriasAdminRoute: typeof MentoriasAdminRoute
  MentoriasGrupoRoute: typeof MentoriasGrupoRoute
  MentoriasGrupoAdminRoute: typeof MentoriasGrupoAdminRoute
  NotasAdminRoute: typeof NotasAdminRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfessorRoute: typeof ProfessorRoute
  ProgressoRoute: typeof ProgressoRoute
  RedacoesRoute: typeof RedacoesRoute
  RedacoesAdminRoute: typeof RedacoesAdminRoute
  SimuladosRoute: typeof SimuladosRoute
  SimuladosAdminRoute: typeof SimuladosAdminRoute
  TemasRedacaoAdminRoute: typeof TemasRedacaoAdminRoute
  TermosRoute: typeof TermosRoute
  ConteudoAdminSecaoRoute: typeof ConteudoAdminSecaoRoute
  ConteudoSecaoRoute: typeof ConteudoSecaoRoute
  EmBreveSecaoRoute: typeof EmBreveSecaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas-redacao-admin': {
      id: '/temas-redacao-admin'
      path: '/temas-redacao-admin'
      fullPath: '/temas-redacao-admin'
      preLoaderRoute: typeof TemasRedacaoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulados-admin': {
      id: '/simulados-admin'
      path: '/simulados-admin'
      fullPath: '/simulados-admin'
      preLoaderRoute: typeof SimuladosAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulados': {
      id: '/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof SimuladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacoes-admin': {
      id: '/redacoes-admin'
      path: '/redacoes-admin'
      fullPath: '/redacoes-admin'
      preLoaderRoute: typeof RedacoesAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacoes': {
      id: '/redacoes'
      path: '/redacoes'
      fullPath: '/redacoes'
      preLoaderRoute: typeof RedacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas-admin': {
      id: '/notas-admin'
      path: '/notas-admin'
      fullPath: '/notas-admin'
      preLoaderRoute: typeof NotasAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias-grupo-admin': {
      id: '/mentorias-grupo-admin'
      path: '/mentorias-grupo-admin'
      fullPath: '/mentorias-grupo-admin'
      preLoaderRoute: typeof MentoriasGrupoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias-grupo': {
      id: '/mentorias-grupo'
      path: '/mentorias-grupo'
      fullPath: '/mentorias-grupo'
      preLoaderRoute: typeof MentoriasGrupoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias-admin': {
      id: '/mentorias-admin'
      path: '/mentorias-admin'
      fullPath: '/mentorias-admin'
      preLoaderRoute: typeof MentoriasAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias': {
      id: '/mentorias'
      path: '/mentorias'
      fullPath: '/mentorias'
      preLoaderRoute: typeof MentoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais-admin': {
      id: '/materiais-admin'
      path: '/materiais-admin'
      fullPath: '/materiais-admin'
      preLoaderRoute: typeof MateriaisAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembretes-admin': {
      id: '/lembretes-admin'
      path: '/lembretes-admin'
      fullPath: '/lembretes-admin'
      preLoaderRoute: typeof LembretesAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas-admin': {
      id: '/aulas-admin'
      path: '/aulas-admin'
      fullPath: '/aulas-admin'
      preLoaderRoute: typeof AulasAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula-ao-vivo-admin': {
      id: '/aula-ao-vivo-admin'
      path: '/aula-ao-vivo-admin'
      fullPath: '/aula-ao-vivo-admin'
      preLoaderRoute: typeof AulaAoVivoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve/$secao': {
      id: '/em-breve/$secao'
      path: '/em-breve/$secao'
      fullPath: '/em-breve/$secao'
      preLoaderRoute: typeof EmBreveSecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/$secao': {
      id: '/conteudo/$secao'
      path: '/conteudo/$secao'
      fullPath: '/conteudo/$secao'
      preLoaderRoute: typeof ConteudoSecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo-admin/$secao': {
      id: '/conteudo-admin/$secao'
      path: '/conteudo-admin/$secao'
      fullPath: '/conteudo-admin/$secao'
      preLoaderRoute: typeof ConteudoAdminSecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  AulaAoVivoAdminRoute: AulaAoVivoAdminRoute,
  AulasRoute: AulasRoute,
  AulasAdminRoute: AulasAdminRoute,
  CalendarioRoute: CalendarioRoute,
  DashboardRoute: DashboardRoute,
  LembretesAdminRoute: LembretesAdminRoute,
  LgpdRoute: LgpdRoute,
  LoginRoute: LoginRoute,
  MateriaisRoute: MateriaisRoute,
  MateriaisAdminRoute: MateriaisAdminRoute,
  MentoriasRoute: MentoriasRoute,
  MentoriasAdminRoute: MentoriasAdminRoute,
  MentoriasGrupoRoute: MentoriasGrupoRoute,
  MentoriasGrupoAdminRoute: MentoriasGrupoAdminRoute,
  NotasAdminRoute: NotasAdminRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfessorRoute: ProfessorRoute,
  ProgressoRoute: ProgressoRoute,
  RedacoesRoute: RedacoesRoute,
  RedacoesAdminRoute: RedacoesAdminRoute,
  SimuladosRoute: SimuladosRoute,
  SimuladosAdminRoute: SimuladosAdminRoute,
  TemasRedacaoAdminRoute: TemasRedacaoAdminRoute,
  TermosRoute: TermosRoute,
  ConteudoAdminSecaoRoute: ConteudoAdminSecaoRoute,
  ConteudoSecaoRoute: ConteudoSecaoRoute,
  EmBreveSecaoRoute: EmBreveSecaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
